name: Workflow 1

on:
  push:
  pull_request:
    branches:
      - master
jobs:
  first-job:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - name: Echo FOO
        env:
          FOO: foo
        run: echo $FOO
